### ISSUE TITLE
"99 LISP Problems" - Acham relevante para a lista exercicios?

### ISSUE THREAD

**Issue by alexandre** [AcademiaDeAlgoritmos/grupo-de-estudos#1]
Tem diversos tipos de problemas (e.g. alguns envolvendo binary trees) e eu acho que pode ser uma boa para o grupo resolver alguns. Comecei a resolver com Racket[0] e agora resolvi retomar do zero.

Se acharem relevante, eu abro um PR adicionando na lista de exercícios. =]

* 99 Problems - https://www.ic.unicamp.br/~meidanis/courses/problemas-lisp/L-99_Ninety-Nine_Lisp_Problems.html

0 - http://docs.racket-lang.org

[ ]'s

**Comment by milazangirolame** [comment]
Adicionar como material de apoio e estudo: Desmistificando Algoritmos, Thomas H. Cormen (Algorithms Unlocked).

**Comment by theomelo** [comment]
Acho sim @alexandre! Cria a PR e relaciona essa issue :)
