### ISSUE TITLE
Conjectura de Collatz - Introdução, algoritmo simples e algumas optimizações

### ISSUE THREAD

**Issue by alexandre** [AcademiaDeAlgoritmos/grupo-de-estudos#6]
Conversando com a @milazangirolame , eu comentei que poderia fazer uma apresentação sobre o famoso problema "3n + 1"[0]. A ideia surgiu de uma lembrança do Garoa +  a apresentação da @milazangirolame envolvendo matemática. A vantagem desse problema é que ele é simples de enunciar e escrever um algoritmo para alguns testes (mesmo sendo um problema em aberto na matemática).

A ideia é falar um pouco do problema em si (um resumo do que encontramos na wikipedia), de como recursão é parte do problema e como pequenas optimizações podem ajudar no dia a dia.

Tudo com pseudo código e deixamos essa issue para discussão e compartilhar links com implementações em linguagens preferidas. No link [0] já tem algumas implementações...podemos pegar algumas para optimizar.

Obs.: Eu vou estou procurando alguma ferramenta para conseguir gravar o meu desktop, mas se não conseguir dá para usar o google hangouts mesmo (com essas opções para live)

0 - https://pt.wikipedia.org/wiki/Conjectura_de_Collatz

**Comment by milazangirolame** [comment]
Acho legal alê! manda um PR! uma sugestão é fazermos em forma de dojo a implementação e já podemos discutir sobre recursividade

**Comment by milazangirolame** [comment]
Olá Ale, sobre seu PR, vou avisar pessoal sobre o conteúdo para prox sexta, e faremos online. QQ coisa criamos um chat no hangouts

**Comment by alexandre** [comment]
Perfeito, @milazangirolame !

Valeu a ajuda :]

**Comment by alexandre** [comment]
Eu estou com alguns problemas pessoais e não vou poder apresentar essa ideia nessa semana. Assim que acertar alguns horários e tarefas, eu abro um PR aqui.

[ ]'s

**Comment by NicolasFrancaX** [comment]
Como funciona essas reuniões? 

É online?

[ ]'s!

**Comment by milazangirolame** [comment]
@NicolasFrancaX sim é online, as sextas 19h30

**Comment by milazangirolame** [comment]
Merged
